// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: cmds.proto

package cmds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandId int32

const (
	CommandId_UNKNOWN                 CommandId = 0
	CommandId_VERSION_GET             CommandId = 1
	CommandId_ADC_CHS_GET             CommandId = 2
	CommandId_ADC_CH_READ             CommandId = 3
	CommandId_PWM_CHS_GET             CommandId = 4
	CommandId_PWM_CH_SET              CommandId = 5
	CommandId_PWM_CH_GET              CommandId = 6
	CommandId_PWM_PERIOD_INTERVAL_GET CommandId = 7
)

// Enum value maps for CommandId.
var (
	CommandId_name = map[int32]string{
		0: "UNKNOWN",
		1: "VERSION_GET",
		2: "ADC_CHS_GET",
		3: "ADC_CH_READ",
		4: "PWM_CHS_GET",
		5: "PWM_CH_SET",
		6: "PWM_CH_GET",
		7: "PWM_PERIOD_INTERVAL_GET",
	}
	CommandId_value = map[string]int32{
		"UNKNOWN":                 0,
		"VERSION_GET":             1,
		"ADC_CHS_GET":             2,
		"ADC_CH_READ":             3,
		"PWM_CHS_GET":             4,
		"PWM_CH_SET":              5,
		"PWM_CH_GET":              6,
		"PWM_PERIOD_INTERVAL_GET": 7,
	}
)

func (x CommandId) Enum() *CommandId {
	p := new(CommandId)
	*p = x
	return p
}

func (x CommandId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandId) Descriptor() protoreflect.EnumDescriptor {
	return file_cmds_proto_enumTypes[0].Descriptor()
}

func (CommandId) Type() protoreflect.EnumType {
	return &file_cmds_proto_enumTypes[0]
}

func (x CommandId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CommandId) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CommandId(num)
	return nil
}

// Deprecated: Use CommandId.Descriptor instead.
func (CommandId) EnumDescriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{0}
}

type RetCode int32

const (
	RetCode_OK                RetCode = 0
	RetCode_ERROR             RetCode = 1
	RetCode_INVALID_ARGUMENT  RetCode = 2
	RetCode_NOT_FOUND         RetCode = 3
	RetCode_PERMISSION_DENIED RetCode = 4
	RetCode_UNAUTHENTICATED   RetCode = 5
	RetCode_ALREADY_EXISTS    RetCode = 6
	RetCode_UNAVAILABLE       RetCode = 7
	RetCode_INTERNAL          RetCode = 8
	RetCode_TIMEOUT           RetCode = 9
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "INVALID_ARGUMENT",
		3: "NOT_FOUND",
		4: "PERMISSION_DENIED",
		5: "UNAUTHENTICATED",
		6: "ALREADY_EXISTS",
		7: "UNAVAILABLE",
		8: "INTERNAL",
		9: "TIMEOUT",
	}
	RetCode_value = map[string]int32{
		"OK":                0,
		"ERROR":             1,
		"INVALID_ARGUMENT":  2,
		"NOT_FOUND":         3,
		"PERMISSION_DENIED": 4,
		"UNAUTHENTICATED":   5,
		"ALREADY_EXISTS":    6,
		"UNAVAILABLE":       7,
		"INTERNAL":          8,
		"TIMEOUT":           9,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cmds_proto_enumTypes[1].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_cmds_proto_enumTypes[1]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RetCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RetCode(num)
	return nil
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{1}
}

type ReqHdr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *CommandId `protobuf:"varint,1,req,name=id,enum=CommandId" json:"id,omitempty"`
}

func (x *ReqHdr) Reset() {
	*x = ReqHdr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHdr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHdr) ProtoMessage() {}

func (x *ReqHdr) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHdr.ProtoReflect.Descriptor instead.
func (*ReqHdr) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{0}
}

func (x *ReqHdr) GetId() CommandId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return CommandId_UNKNOWN
}

type ResHdr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *CommandId `protobuf:"varint,1,req,name=id,enum=CommandId" json:"id,omitempty"`
	Ret    *RetCode   `protobuf:"varint,2,opt,name=ret,enum=RetCode" json:"ret,omitempty"`
	ErrMsg *string    `protobuf:"bytes,3,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
}

func (x *ResHdr) Reset() {
	*x = ResHdr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResHdr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResHdr) ProtoMessage() {}

func (x *ResHdr) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResHdr.ProtoReflect.Descriptor instead.
func (*ResHdr) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{1}
}

func (x *ResHdr) GetId() CommandId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return CommandId_UNKNOWN
}

func (x *ResHdr) GetRet() RetCode {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return RetCode_OK
}

func (x *ResHdr) GetErrMsg() string {
	if x != nil && x.ErrMsg != nil {
		return *x.ErrMsg
	}
	return ""
}

type VersionGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VersionGetReq) Reset() {
	*x = VersionGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionGetReq) ProtoMessage() {}

func (x *VersionGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionGetReq.ProtoReflect.Descriptor instead.
func (*VersionGetReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{2}
}

type VersionGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    *uint32 `protobuf:"fixed32,1,opt,name=version" json:"version,omitempty"`
	Branch     *string `protobuf:"bytes,2,opt,name=branch" json:"branch,omitempty"`
	Sha1       *string `protobuf:"bytes,3,opt,name=sha1" json:"sha1,omitempty"`
	CommitDate *string `protobuf:"bytes,4,opt,name=commit_date,json=commitDate" json:"commit_date,omitempty"`
}

func (x *VersionGetRes) Reset() {
	*x = VersionGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionGetRes) ProtoMessage() {}

func (x *VersionGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionGetRes.ProtoReflect.Descriptor instead.
func (*VersionGetRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{3}
}

func (x *VersionGetRes) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *VersionGetRes) GetBranch() string {
	if x != nil && x.Branch != nil {
		return *x.Branch
	}
	return ""
}

func (x *VersionGetRes) GetSha1() string {
	if x != nil && x.Sha1 != nil {
		return *x.Sha1
	}
	return ""
}

func (x *VersionGetRes) GetCommitDate() string {
	if x != nil && x.CommitDate != nil {
		return *x.CommitDate
	}
	return ""
}

type AdcChsGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdcChsGetReq) Reset() {
	*x = AdcChsGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdcChsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdcChsGetReq) ProtoMessage() {}

func (x *AdcChsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdcChsGetReq.ProtoReflect.Descriptor instead.
func (*AdcChsGetReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{4}
}

type AdcChsGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdcChs *uint32 `protobuf:"fixed32,1,opt,name=adc_chs,json=adcChs" json:"adc_chs,omitempty"`
}

func (x *AdcChsGetRes) Reset() {
	*x = AdcChsGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdcChsGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdcChsGetRes) ProtoMessage() {}

func (x *AdcChsGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdcChsGetRes.ProtoReflect.Descriptor instead.
func (*AdcChsGetRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{5}
}

func (x *AdcChsGetRes) GetAdcChs() uint32 {
	if x != nil && x.AdcChs != nil {
		return *x.AdcChs
	}
	return 0
}

type AdcChReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ch *uint32 `protobuf:"fixed32,1,req,name=ch" json:"ch,omitempty"`
}

func (x *AdcChReadReq) Reset() {
	*x = AdcChReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdcChReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdcChReadReq) ProtoMessage() {}

func (x *AdcChReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdcChReadReq.ProtoReflect.Descriptor instead.
func (*AdcChReadReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{6}
}

func (x *AdcChReadReq) GetCh() uint32 {
	if x != nil && x.Ch != nil {
		return *x.Ch
	}
	return 0
}

type AdcChReadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val *uint32 `protobuf:"fixed32,1,opt,name=val" json:"val,omitempty"`
}

func (x *AdcChReadRes) Reset() {
	*x = AdcChReadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdcChReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdcChReadRes) ProtoMessage() {}

func (x *AdcChReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdcChReadRes.ProtoReflect.Descriptor instead.
func (*AdcChReadRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{7}
}

func (x *AdcChReadRes) GetVal() uint32 {
	if x != nil && x.Val != nil {
		return *x.Val
	}
	return 0
}

type PwmChsGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PwmChsGetReq) Reset() {
	*x = PwmChsGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmChsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmChsGetReq) ProtoMessage() {}

func (x *PwmChsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmChsGetReq.ProtoReflect.Descriptor instead.
func (*PwmChsGetReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{8}
}

type PwmChsGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PwmChs *uint32 `protobuf:"fixed32,1,opt,name=pwm_chs,json=pwmChs" json:"pwm_chs,omitempty"`
}

func (x *PwmChsGetRes) Reset() {
	*x = PwmChsGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmChsGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmChsGetRes) ProtoMessage() {}

func (x *PwmChsGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmChsGetRes.ProtoReflect.Descriptor instead.
func (*PwmChsGetRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{9}
}

func (x *PwmChsGetRes) GetPwmChs() uint32 {
	if x != nil && x.PwmChs != nil {
		return *x.PwmChs
	}
	return 0
}

type PwmChSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ch     *uint32 `protobuf:"fixed32,1,req,name=ch" json:"ch,omitempty"`
	Period *uint32 `protobuf:"varint,2,req,name=period" json:"period,omitempty"`
	Pulse  *uint32 `protobuf:"varint,3,req,name=pulse" json:"pulse,omitempty"`
}

func (x *PwmChSetReq) Reset() {
	*x = PwmChSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmChSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmChSetReq) ProtoMessage() {}

func (x *PwmChSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmChSetReq.ProtoReflect.Descriptor instead.
func (*PwmChSetReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{10}
}

func (x *PwmChSetReq) GetCh() uint32 {
	if x != nil && x.Ch != nil {
		return *x.Ch
	}
	return 0
}

func (x *PwmChSetReq) GetPeriod() uint32 {
	if x != nil && x.Period != nil {
		return *x.Period
	}
	return 0
}

func (x *PwmChSetReq) GetPulse() uint32 {
	if x != nil && x.Pulse != nil {
		return *x.Pulse
	}
	return 0
}

type PwmChSetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PwmChSetRes) Reset() {
	*x = PwmChSetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmChSetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmChSetRes) ProtoMessage() {}

func (x *PwmChSetRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmChSetRes.ProtoReflect.Descriptor instead.
func (*PwmChSetRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{11}
}

type PwmChGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ch *uint32 `protobuf:"fixed32,1,req,name=ch" json:"ch,omitempty"`
}

func (x *PwmChGetReq) Reset() {
	*x = PwmChGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmChGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmChGetReq) ProtoMessage() {}

func (x *PwmChGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmChGetReq.ProtoReflect.Descriptor instead.
func (*PwmChGetReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{12}
}

func (x *PwmChGetReq) GetCh() uint32 {
	if x != nil && x.Ch != nil {
		return *x.Ch
	}
	return 0
}

type PwmChGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period *uint32 `protobuf:"varint,1,req,name=period" json:"period,omitempty"`
	Pulse  *uint32 `protobuf:"varint,2,req,name=pulse" json:"pulse,omitempty"`
}

func (x *PwmChGetRes) Reset() {
	*x = PwmChGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmChGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmChGetRes) ProtoMessage() {}

func (x *PwmChGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmChGetRes.ProtoReflect.Descriptor instead.
func (*PwmChGetRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{13}
}

func (x *PwmChGetRes) GetPeriod() uint32 {
	if x != nil && x.Period != nil {
		return *x.Period
	}
	return 0
}

func (x *PwmChGetRes) GetPulse() uint32 {
	if x != nil && x.Pulse != nil {
		return *x.Pulse
	}
	return 0
}

type PwmPeriodsGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PwmPeriodsGetReq) Reset() {
	*x = PwmPeriodsGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmPeriodsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmPeriodsGetReq) ProtoMessage() {}

func (x *PwmPeriodsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmPeriodsGetReq.ProtoReflect.Descriptor instead.
func (*PwmPeriodsGetReq) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{14}
}

type PwmPeriodsGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeriodMin *uint32 `protobuf:"varint,1,req,name=period_min,json=periodMin" json:"period_min,omitempty"`
	PeriodMax *uint32 `protobuf:"varint,2,req,name=period_max,json=periodMax" json:"period_max,omitempty"`
}

func (x *PwmPeriodsGetRes) Reset() {
	*x = PwmPeriodsGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PwmPeriodsGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PwmPeriodsGetRes) ProtoMessage() {}

func (x *PwmPeriodsGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PwmPeriodsGetRes.ProtoReflect.Descriptor instead.
func (*PwmPeriodsGetRes) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{15}
}

func (x *PwmPeriodsGetRes) GetPeriodMin() uint32 {
	if x != nil && x.PeriodMin != nil {
		return *x.PeriodMin
	}
	return 0
}

func (x *PwmPeriodsGetRes) GetPeriodMax() uint32 {
	if x != nil && x.PeriodMax != nil {
		return *x.PeriodMax
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hdr *ReqHdr `protobuf:"bytes,1,req,name=hdr" json:"hdr,omitempty"`
	// Types that are assignable to Pl:
	//
	//	*Request_VersionGet
	//	*Request_AdcChsGet
	//	*Request_AdcChRead
	//	*Request_PwmChsGet
	//	*Request_PwmChSet
	//	*Request_PwmChGet
	//	*Request_PwmPeriodsGet
	Pl isRequest_Pl `protobuf_oneof:"pl"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{16}
}

func (x *Request) GetHdr() *ReqHdr {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (m *Request) GetPl() isRequest_Pl {
	if m != nil {
		return m.Pl
	}
	return nil
}

func (x *Request) GetVersionGet() *VersionGetReq {
	if x, ok := x.GetPl().(*Request_VersionGet); ok {
		return x.VersionGet
	}
	return nil
}

func (x *Request) GetAdcChsGet() *AdcChsGetReq {
	if x, ok := x.GetPl().(*Request_AdcChsGet); ok {
		return x.AdcChsGet
	}
	return nil
}

func (x *Request) GetAdcChRead() *AdcChReadReq {
	if x, ok := x.GetPl().(*Request_AdcChRead); ok {
		return x.AdcChRead
	}
	return nil
}

func (x *Request) GetPwmChsGet() *PwmChsGetReq {
	if x, ok := x.GetPl().(*Request_PwmChsGet); ok {
		return x.PwmChsGet
	}
	return nil
}

func (x *Request) GetPwmChSet() *PwmChSetReq {
	if x, ok := x.GetPl().(*Request_PwmChSet); ok {
		return x.PwmChSet
	}
	return nil
}

func (x *Request) GetPwmChGet() *PwmChGetReq {
	if x, ok := x.GetPl().(*Request_PwmChGet); ok {
		return x.PwmChGet
	}
	return nil
}

func (x *Request) GetPwmPeriodsGet() *PwmPeriodsGetReq {
	if x, ok := x.GetPl().(*Request_PwmPeriodsGet); ok {
		return x.PwmPeriodsGet
	}
	return nil
}

type isRequest_Pl interface {
	isRequest_Pl()
}

type Request_VersionGet struct {
	VersionGet *VersionGetReq `protobuf:"bytes,2,opt,name=version_get,json=versionGet,oneof"`
}

type Request_AdcChsGet struct {
	AdcChsGet *AdcChsGetReq `protobuf:"bytes,3,opt,name=adc_chs_get,json=adcChsGet,oneof"`
}

type Request_AdcChRead struct {
	AdcChRead *AdcChReadReq `protobuf:"bytes,4,opt,name=adc_ch_read,json=adcChRead,oneof"`
}

type Request_PwmChsGet struct {
	PwmChsGet *PwmChsGetReq `protobuf:"bytes,5,opt,name=pwm_chs_get,json=pwmChsGet,oneof"`
}

type Request_PwmChSet struct {
	PwmChSet *PwmChSetReq `protobuf:"bytes,6,opt,name=pwm_ch_set,json=pwmChSet,oneof"`
}

type Request_PwmChGet struct {
	PwmChGet *PwmChGetReq `protobuf:"bytes,7,opt,name=pwm_ch_get,json=pwmChGet,oneof"`
}

type Request_PwmPeriodsGet struct {
	PwmPeriodsGet *PwmPeriodsGetReq `protobuf:"bytes,8,opt,name=pwm_periods_get,json=pwmPeriodsGet,oneof"`
}

func (*Request_VersionGet) isRequest_Pl() {}

func (*Request_AdcChsGet) isRequest_Pl() {}

func (*Request_AdcChRead) isRequest_Pl() {}

func (*Request_PwmChsGet) isRequest_Pl() {}

func (*Request_PwmChSet) isRequest_Pl() {}

func (*Request_PwmChGet) isRequest_Pl() {}

func (*Request_PwmPeriodsGet) isRequest_Pl() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hdr *ResHdr `protobuf:"bytes,1,req,name=hdr" json:"hdr,omitempty"`
	// Types that are assignable to Pl:
	//
	//	*Response_VersionGet
	//	*Response_AdcChsGet
	//	*Response_AdcChRead
	//	*Response_PwmChsGet
	//	*Response_PwmChSet
	//	*Response_PwmChGet
	//	*Response_PwmPeriodsGet
	Pl isResponse_Pl `protobuf_oneof:"pl"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{17}
}

func (x *Response) GetHdr() *ResHdr {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (m *Response) GetPl() isResponse_Pl {
	if m != nil {
		return m.Pl
	}
	return nil
}

func (x *Response) GetVersionGet() *VersionGetRes {
	if x, ok := x.GetPl().(*Response_VersionGet); ok {
		return x.VersionGet
	}
	return nil
}

func (x *Response) GetAdcChsGet() *AdcChsGetRes {
	if x, ok := x.GetPl().(*Response_AdcChsGet); ok {
		return x.AdcChsGet
	}
	return nil
}

func (x *Response) GetAdcChRead() *AdcChReadRes {
	if x, ok := x.GetPl().(*Response_AdcChRead); ok {
		return x.AdcChRead
	}
	return nil
}

func (x *Response) GetPwmChsGet() *PwmChsGetRes {
	if x, ok := x.GetPl().(*Response_PwmChsGet); ok {
		return x.PwmChsGet
	}
	return nil
}

func (x *Response) GetPwmChSet() *PwmChSetRes {
	if x, ok := x.GetPl().(*Response_PwmChSet); ok {
		return x.PwmChSet
	}
	return nil
}

func (x *Response) GetPwmChGet() *PwmChGetRes {
	if x, ok := x.GetPl().(*Response_PwmChGet); ok {
		return x.PwmChGet
	}
	return nil
}

func (x *Response) GetPwmPeriodsGet() *PwmPeriodsGetRes {
	if x, ok := x.GetPl().(*Response_PwmPeriodsGet); ok {
		return x.PwmPeriodsGet
	}
	return nil
}

type isResponse_Pl interface {
	isResponse_Pl()
}

type Response_VersionGet struct {
	VersionGet *VersionGetRes `protobuf:"bytes,2,opt,name=version_get,json=versionGet,oneof"`
}

type Response_AdcChsGet struct {
	AdcChsGet *AdcChsGetRes `protobuf:"bytes,3,opt,name=adc_chs_get,json=adcChsGet,oneof"`
}

type Response_AdcChRead struct {
	AdcChRead *AdcChReadRes `protobuf:"bytes,4,opt,name=adc_ch_read,json=adcChRead,oneof"`
}

type Response_PwmChsGet struct {
	PwmChsGet *PwmChsGetRes `protobuf:"bytes,5,opt,name=pwm_chs_get,json=pwmChsGet,oneof"`
}

type Response_PwmChSet struct {
	PwmChSet *PwmChSetRes `protobuf:"bytes,6,opt,name=pwm_ch_set,json=pwmChSet,oneof"`
}

type Response_PwmChGet struct {
	PwmChGet *PwmChGetRes `protobuf:"bytes,7,opt,name=pwm_ch_get,json=pwmChGet,oneof"`
}

type Response_PwmPeriodsGet struct {
	PwmPeriodsGet *PwmPeriodsGetRes `protobuf:"bytes,8,opt,name=pwm_periods_get,json=pwmPeriodsGet,oneof"`
}

func (*Response_VersionGet) isResponse_Pl() {}

func (*Response_AdcChsGet) isResponse_Pl() {}

func (*Response_AdcChRead) isResponse_Pl() {}

func (*Response_PwmChsGet) isResponse_Pl() {}

func (*Response_PwmChSet) isResponse_Pl() {}

func (*Response_PwmChGet) isResponse_Pl() {}

func (*Response_PwmPeriodsGet) isResponse_Pl() {}

var File_cmds_proto protoreflect.FileDescriptor

var file_cmds_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6d, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x5f, 0x68, 0x64, 0x72, 0x12, 0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x5c, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x5f, 0x68, 0x64, 0x72, 0x12,
	0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x72, 0x65, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x17, 0x0a, 0x0f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65,
	0x74, 0x5f, 0x72, 0x65, 0x71, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x78, 0x0a, 0x0f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x61, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x68, 0x61, 0x31, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0x17, 0x0a, 0x0f, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x73,
	0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x2a,
	0x0a, 0x0f, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x06, 0x61, 0x64, 0x63, 0x43, 0x68, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x61, 0x64,
	0x63, 0x5f, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x63, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x63, 0x68, 0x22, 0x23, 0x0a,
	0x0f, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x22, 0x17, 0x0a, 0x0f, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65,
	0x74, 0x5f, 0x72, 0x65, 0x71, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x2a, 0x0a, 0x0f, 0x70,
	0x77, 0x6d, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x06, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x73, 0x22, 0x4e, 0x0a, 0x0e, 0x70, 0x77, 0x6d, 0x5f, 0x63,
	0x68, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x05, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x0e, 0x70, 0x77, 0x6d, 0x5f, 0x63,
	0x68, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22,
	0x20, 0x0a, 0x0e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x63,
	0x68, 0x22, 0x3e, 0x0a, 0x0e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x75, 0x6c, 0x73, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x75, 0x6c, 0x73,
	0x65, 0x22, 0x1b, 0x0a, 0x13, 0x70, 0x77, 0x6d, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73,
	0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x53,
	0x0a, 0x13, 0x70, 0x77, 0x6d, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x5f, 0x67, 0x65,
	0x74, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f,
	0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x4d, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x6d,
	0x61, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x4d, 0x61, 0x78, 0x22, 0x9e, 0x03, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x03, 0x68, 0x64, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72,
	0x65, 0x71, 0x5f, 0x68, 0x64, 0x72, 0x52, 0x03, 0x68, 0x64, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74,
	0x12, 0x32, 0x0a, 0x0b, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x73, 0x5f,
	0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x61, 0x64, 0x63, 0x43, 0x68,
	0x73, 0x47, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x63, 0x5f,
	0x63, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x61,
	0x64, 0x63, 0x43, 0x68, 0x52, 0x65, 0x61, 0x64, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x77, 0x6d, 0x5f,
	0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x48,
	0x00, 0x52, 0x09, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x73, 0x47, 0x65, 0x74, 0x12, 0x2f, 0x0a, 0x0a,
	0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x48, 0x00, 0x52, 0x08, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x53, 0x65, 0x74, 0x12, 0x2f, 0x0a,
	0x0a, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x08, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x47, 0x65, 0x74, 0x12, 0x3e,
	0x0a, 0x0f, 0x70, 0x77, 0x6d, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x5f, 0x67, 0x65,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x77, 0x6d, 0x5f, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x0d, 0x70, 0x77, 0x6d, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x47, 0x65, 0x74, 0x42, 0x04,
	0x0a, 0x02, 0x70, 0x6c, 0x22, 0x9f, 0x03, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x03, 0x68, 0x64, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x72, 0x65, 0x73, 0x5f, 0x68, 0x64, 0x72, 0x52, 0x03, 0x68, 0x64, 0x72, 0x12, 0x33, 0x0a,
	0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x74,
	0x5f, 0x72, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47,
	0x65, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68,
	0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x61, 0x64, 0x63,
	0x43, 0x68, 0x73, 0x47, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x61, 0x64, 0x63, 0x5f, 0x63, 0x68,
	0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64,
	0x63, 0x5f, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x09, 0x61, 0x64, 0x63, 0x43, 0x68, 0x52, 0x65, 0x61, 0x64, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x77,
	0x6d, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x48, 0x00, 0x52, 0x09, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x73, 0x47, 0x65, 0x74, 0x12, 0x2f,
	0x0a, 0x0a, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x53, 0x65, 0x74, 0x12,
	0x2f, 0x0a, 0x0a, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x77, 0x6d, 0x5f, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74,
	0x5f, 0x72, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x77, 0x6d, 0x43, 0x68, 0x47, 0x65, 0x74,
	0x12, 0x3e, 0x0a, 0x0f, 0x70, 0x77, 0x6d, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x5f,
	0x67, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x77, 0x6d, 0x5f,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x0d, 0x70, 0x77, 0x6d, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x47, 0x65, 0x74,
	0x42, 0x04, 0x0a, 0x02, 0x70, 0x6c, 0x2a, 0x9a, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x5f, 0x69, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x45,
	0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x43, 0x5f, 0x43, 0x48, 0x53, 0x5f, 0x47,
	0x45, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x43, 0x5f, 0x43, 0x48, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x57, 0x4d, 0x5f, 0x43, 0x48, 0x53,
	0x5f, 0x47, 0x45, 0x54, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x57, 0x4d, 0x5f, 0x43, 0x48,
	0x5f, 0x53, 0x45, 0x54, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x57, 0x4d, 0x5f, 0x43, 0x48,
	0x5f, 0x47, 0x45, 0x54, 0x10, 0x06, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x57, 0x4d, 0x5f, 0x50, 0x45,
	0x52, 0x49, 0x4f, 0x44, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x5f, 0x47, 0x45,
	0x54, 0x10, 0x07, 0x2a, 0xae, 0x01, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41,
	0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54,
	0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d,
	0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x04, 0x12,
	0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x41, 0x56,
	0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f,
	0x55, 0x54, 0x10, 0x09,
}

var (
	file_cmds_proto_rawDescOnce sync.Once
	file_cmds_proto_rawDescData = file_cmds_proto_rawDesc
)

func file_cmds_proto_rawDescGZIP() []byte {
	file_cmds_proto_rawDescOnce.Do(func() {
		file_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmds_proto_rawDescData)
	})
	return file_cmds_proto_rawDescData
}

var file_cmds_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cmds_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cmds_proto_goTypes = []interface{}{
	(CommandId)(0),           // 0: command_id
	(RetCode)(0),             // 1: ret_code
	(*ReqHdr)(nil),           // 2: req_hdr
	(*ResHdr)(nil),           // 3: res_hdr
	(*VersionGetReq)(nil),    // 4: version_get_req
	(*VersionGetRes)(nil),    // 5: version_get_res
	(*AdcChsGetReq)(nil),     // 6: adc_chs_get_req
	(*AdcChsGetRes)(nil),     // 7: adc_chs_get_res
	(*AdcChReadReq)(nil),     // 8: adc_ch_read_req
	(*AdcChReadRes)(nil),     // 9: adc_ch_read_res
	(*PwmChsGetReq)(nil),     // 10: pwm_chs_get_req
	(*PwmChsGetRes)(nil),     // 11: pwm_chs_get_res
	(*PwmChSetReq)(nil),      // 12: pwm_ch_set_req
	(*PwmChSetRes)(nil),      // 13: pwm_ch_set_res
	(*PwmChGetReq)(nil),      // 14: pwm_ch_get_req
	(*PwmChGetRes)(nil),      // 15: pwm_ch_get_res
	(*PwmPeriodsGetReq)(nil), // 16: pwm_periods_get_req
	(*PwmPeriodsGetRes)(nil), // 17: pwm_periods_get_res
	(*Request)(nil),          // 18: request
	(*Response)(nil),         // 19: response
}
var file_cmds_proto_depIdxs = []int32{
	0,  // 0: req_hdr.id:type_name -> command_id
	0,  // 1: res_hdr.id:type_name -> command_id
	1,  // 2: res_hdr.ret:type_name -> ret_code
	2,  // 3: request.hdr:type_name -> req_hdr
	4,  // 4: request.version_get:type_name -> version_get_req
	6,  // 5: request.adc_chs_get:type_name -> adc_chs_get_req
	8,  // 6: request.adc_ch_read:type_name -> adc_ch_read_req
	10, // 7: request.pwm_chs_get:type_name -> pwm_chs_get_req
	12, // 8: request.pwm_ch_set:type_name -> pwm_ch_set_req
	14, // 9: request.pwm_ch_get:type_name -> pwm_ch_get_req
	16, // 10: request.pwm_periods_get:type_name -> pwm_periods_get_req
	3,  // 11: response.hdr:type_name -> res_hdr
	5,  // 12: response.version_get:type_name -> version_get_res
	7,  // 13: response.adc_chs_get:type_name -> adc_chs_get_res
	9,  // 14: response.adc_ch_read:type_name -> adc_ch_read_res
	11, // 15: response.pwm_chs_get:type_name -> pwm_chs_get_res
	13, // 16: response.pwm_ch_set:type_name -> pwm_ch_set_res
	15, // 17: response.pwm_ch_get:type_name -> pwm_ch_get_res
	17, // 18: response.pwm_periods_get:type_name -> pwm_periods_get_res
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_cmds_proto_init() }
func file_cmds_proto_init() {
	if File_cmds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmds_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHdr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResHdr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdcChsGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdcChsGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdcChReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdcChReadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmChsGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmChsGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmChSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmChSetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmChGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmChGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmPeriodsGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PwmPeriodsGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmds_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*Request_VersionGet)(nil),
		(*Request_AdcChsGet)(nil),
		(*Request_AdcChRead)(nil),
		(*Request_PwmChsGet)(nil),
		(*Request_PwmChSet)(nil),
		(*Request_PwmChGet)(nil),
		(*Request_PwmPeriodsGet)(nil),
	}
	file_cmds_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*Response_VersionGet)(nil),
		(*Response_AdcChsGet)(nil),
		(*Response_AdcChRead)(nil),
		(*Response_PwmChsGet)(nil),
		(*Response_PwmChSet)(nil),
		(*Response_PwmChGet)(nil),
		(*Response_PwmPeriodsGet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmds_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmds_proto_goTypes,
		DependencyIndexes: file_cmds_proto_depIdxs,
		EnumInfos:         file_cmds_proto_enumTypes,
		MessageInfos:      file_cmds_proto_msgTypes,
	}.Build()
	File_cmds_proto = out.File
	file_cmds_proto_rawDesc = nil
	file_cmds_proto_goTypes = nil
	file_cmds_proto_depIdxs = nil
}
